name: Flutter Web CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Create config.dart with secret
        run: |
          mkdir -p lib/config
          echo "class AppConfig {" > lib/config.dart
          echo "static final BASE_URL = \"${{ secrets.BASE_URL }}\";" >> lib/config.dart
          echo "}" >> lib/config.dart

      - name: Analyze project
        run: flutter analyze || true

      - name: Run tests
        run: flutter test

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web
